#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlashCardSampleGame.Android.Resource", IsApplication=true)]

namespace FlashCardSampleGame.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BasicPrimitiveBuddy.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::FilenameBuddy.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::FlashCards.Android.Resource.String.ApplicationName = global::FlashCardSampleGame.Android.Resource.String.ApplicationName;
			global::FlashCards.Android.Resource.String.Hello = global::FlashCardSampleGame.Android.Resource.String.Hello;
			global::FlashCards.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::FontBuddyLib.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::GameTimer.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::HadoukInput.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::ListExtensions.Android.Resource.String.ApplicationName = global::FlashCardSampleGame.Android.Resource.String.ApplicationName;
			global::ListExtensions.Android.Resource.String.Hello = global::FlashCardSampleGame.Android.Resource.String.Hello;
			global::MatrixExtensions.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::MenuBuddy.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::ResolutionBuddy.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::TetrisRandomizer.Android.Resource.String.ApplicationName = global::FlashCardSampleGame.Android.Resource.String.ApplicationName;
			global::TetrisRandomizer.Android.Resource.String.Hello = global::FlashCardSampleGame.Android.Resource.String.Hello;
			global::TouchScreenBuddy.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
			global::XmlBuddy.Android.Resource.String.library_name = global::FlashCardSampleGame.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
